pkg load control;
pkg load signal;

function abrirVentanaPrincipal ()
  ventanaPrincipal = figure;
  set (ventanaPrincipal,"name","AMIC - Aproximacion por Mínimos Cuadrados");
  set (ventanaPrincipal,"numbertitle","off");
  set (ventanaPrincipal,"color",[.5,.5,.5]);
  set (ventanaPrincipal,"menubar","none"); #barra de menu principal y herramientas desaparecen

  entornoPrincipal = uibuttongroup (ventanaPrincipal, "position", [ 0 0 1 1], ...
                 "title","Elija una opccion", ...
                 "titleposition","centertop","fontsize",11,"fontname","Arial");
             
  botonCoeficientes = uicontrol (entornoPrincipal,"string","Aproximar", ...
                 "position",[125,250,300,100],"callback",{@abrirVentanaAproximar}, ...
                 "backgroundcolor",[.8,.8,.8]);
  botonPCG = uicontrol (entornoPrincipal,"string","Comparar Aproximaciones", ...
                 "position",[125,100,300,100],"callback",{@abrirVentanaComAprox}, ...
                 "backgroundcolor",[.8,.8,.8]);
endfunction

              
function abrirVentanaAproximar (handlesource,event)
  ventanaAproximar = figure;
  set (ventanaAproximar,"name","Aproximacion por minimos cuadrados");
  set (ventanaAproximar,"numbertitle","off");
  
  entornoAproximar = uibuttongroup (ventanaAproximar, "position", [ 0 0 1 1], ...
               "title","Establezca los puntos y elija su aproximacion","titleposition","centertop");
               
  textoEjeX = uicontrol (entornoAproximar,"style","text", ...
               "string","eje x:","position",[10,350,300,40], ... 
               "fontsize",16);  
  ejeX = uicontrol (entornoAproximar, "style", "edit", ...
               "string", "2,7,4", "position",[20,310,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);              
               
  textoEjeY = uicontrol (entornoAproximar,"style","text", ...
               "string","Eje y :","position",[10,250,300,40], ... 
               "fontsize",16);  
  ejeY = uicontrol (entornoAproximar, "style", "edit", ...
               "string", "6,1,9,3", "position",[20,210,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);
               
  botonMostrarRecta = uicontrol (entornoAproximar,"string"," Recta", ...
               "position",[390,350,100,30],"callback",...
                {@mostrarRecta,ejeX,ejeY}, ...
              
               "backgroundcolor",[.8,.8,.8]);
  botonCalculosRecta = uicontrol (entornoAproximar,"string","calculos recta", ...
               "position",[500,350,100,30],"callback",...
               {@mostrarPolos,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonRectaConPuntos = uicontrol (entornoAproximar,"string"," Recta con puntos", ...
               "position",[650,350,150,30],"callback",...
                {@mostrarPolos,ejeX,ejeY,0,false}, ...
                          
               "backgroundcolor",[.8,.8,.8]);             
  botonParabola = uicontrol (entornoAproximar,"string","Parabola", ...
               "position",[390,300,150,30],"callback",...
               {@mostrarPolos,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonCalculosParabola = uicontrol (entornoAproximar,"string"," calculos parabola", ...
               "position",[550,300,100,30],"callback",...
               {@mostrarPolos,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonParabolaConPuntos = uicontrol (entornoAproximar,"string"," parabola con puntos", ...
               "position",[700,300,150,30],"callback",...
                {@mostrarPolos,ejeX,ejeY,0,false}, ...
                "backgroundcolor",[.8,.8,.8]);
  botonExponencial = uicontrol (entornoAproximar,"string","Exponencial", ...
               "position",[390,250,150,30],"callback",...
               {@mostrarCeros,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonPotencial = uicontrol (entornoAproximar,"string","Potencial", ...
               "position",[390,200,150,30],"callback",...
               {@mostrarGanancia,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonHiperbola = uicontrol (entornoAproximar,"string","Hiperbola", ...
               "position",[390,150,150,30],"callback",...
               {@mostrarExpresionCPG,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonGraficar = uicontrol (entornoAproximar,"string","Graficar ceros y polos", ...
               "position",[390,100,150,30],"callback",...
               {@mostrarGrafico,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonEstabilidad = uicontrol (entornoAproximar,"string","Indicar estabilidad", ...
               "position",[390,50,150,30],"callback",...
               {@mostrarEstabilidad,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonTodo = uicontrol (entornoAproximar,"string","Analizar todo", ...
               "position",[60,80,200,50],"callback",...
               {@mostrarTodo,ejeX,ejeY,0,false}, ...
               "backgroundcolor",[.2,.8,.2],"fontsize",16);
endfunction


function abrirVentanaComAprox (handlesource,event)
  ventanaCPG = figure;
  set (ventanaCPG,"name","Función de transferencia: Ceros, polos y ganancia");
  set (ventanaCPG,"numbertitle","off");
  
  entornoCPG = uibuttongroup (ventanaCPG, "position", [ 0 0 1 1], ...
               "title","Establezca los ceros, polos y ganancia y elija su opción", ...
               "titleposition","centertop");
               
  textoCeros = uicontrol (entornoCPG,"style","text", ...
               "string","Ceros:","position",[40,320,80,40], ... 
               "fontsize",16);  
  ceros = uicontrol (entornoCPG, "style", "edit", ...
               "string", "1,1,3", "position",[150,320,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);        
               
  textoPolos = uicontrol (entornoCPG,"style","text", ...
               "string","Polos:","position",[40,250,80,40], ... 
               "fontsize",16);  
  polos = uicontrol (entornoCPG, "style", "edit", ...
               "string", "3,4,5,6", "position",[150,250,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);  
               
  textoGanancia = uicontrol (entornoCPG,"style","text", ...
               "string","Ganancia:","position",[40,180,100,40], ... 
               "fontsize",16);  
  ganancia = uicontrol (entornoCPG, "style", "edit", ...
               "string", "5", "position",[150,180,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);  
               
  botonExpresion = uicontrol (entornoCPG,"string","Expresión", ...
               "position",[390,350,150,30],"callback", ...
               {@mostrarExpresion,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonPolos = uicontrol (entornoCPG,"string","Polos", ...
               "position",[390,300,150,30],"callback",...
               {@mostrarPolos,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonCeros = uicontrol (entornoCPG,"string","Ceros", ...
               "position",[390,250,150,30],"callback",...
               {@mostrarCeros,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonGanancia = uicontrol (entornoCPG,"string","Ganancia", ...
               "position",[390,200,150,30],"callback",...
               {@mostrarGanancia,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonExpresionCPG = uicontrol (entornoCPG,"string","Expresión C-P-G", ...
               "position",[390,150,150,30],"callback",...
               {@mostrarExpresionCPG,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonGraficar = uicontrol (entornoCPG,"string","Graficar ceros y polos", ...
               "position",[390,100,150,30],"callback",...
               {@mostrarGrafico,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonEstabilidad = uicontrol (entornoCPG,"string","Indicar estabilidad", ...
               "position",[390,50,150,30],"callback",...
               {@mostrarEstabilidad,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.8,.8,.8]);
  botonTodo = uicontrol (entornoCPG,"string","Analizar todo", ...
               "position",[60,80,200,50],"callback",...
               {@mostrarTodo,ceros,polos,ganancia,true}, ...
               "backgroundcolor",[.2,.8,.2],"fontsize",16);
endfunction
function mostrarRecta (ejex,ejey)
   
  grafico = figure;
  set (grafico,"name","Grafico de la recta aproximante");
  set (grafico,"numbertitle","off");
  nums1 = stringAArray (get (ejex,"string"));  
  nums2 = stringAArray (get (ejey,"string"));
 # x = ejex
 # errordlg("el numero de x es %s",ejex);
 # y= ejey
  plot(nums1,nums2);
  title ("Recta ");
  xlabel ("Eje real");
  ylabel ("Eje y");
endfunction 

function funcionTransferencia = obtenerFT (nums1,nums2,ganancia) 
  if (ganancia == 0)
    funcionTransferencia = tf(nums1,nums2);
  else
    funcionTransferencia = zpk(nums1,nums2,ganancia);
  endif
endfunction
  
function array = stringAArray (str)
    charArray = strsplit(str,",");
    array = [];
    len = length (charArray);
    for i = 1:len
        array(i) = str2double (charArray{i});
    endfor
endfunction 

function ft = procesarFT (numBox,denBox,gainBox,hayGanancia)
  ganancia = 0;
  nums1 = stringAArray (get (numBox,"string"));  
  nums2 = stringAArray (get (denBox,"string"));
  if (hayGanancia)
    ganancia = str2double (get (gainBox,"string"));
    if (ganancia == 0)
      warndlg ("No puede tener una ganancia de 0","Error");
      return;
    endif
  endif
  ft = obtenerFT(nums1,nums2,ganancia);
endfunction
 
function mostrarExpresion (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  helpdlg (evalc ("ft"),"Expresion de la funcion de transferencia"); 
endfunction

function mostrarPolos (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  [z,p,g] = tf2zp(ft);
  helpdlg (evalc ("p"),"Polos");
endfunction

function mostrarCeros (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  [z,p,g] = tf2zp(ft);
  helpdlg (evalc ("z"),"Ceros");
endfunction

function mostrarGanancia (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  [z,p,g] = tf2zp(ft);
  helpdlg (evalc ("g"),"Ganancia");
endfunction

function str = obtenerExpresionCPG (ft)
  [z,p,g] = tf2zp(ft);
  str = num2str (g);
  cantidadceros = length (z);
  cantidadpolos = length (p);
  for i = 1:cantidadceros 
    str = strcat(str, " [s - (",num2str (z(i)),")] ");
  endfor   
  str = strcat(str, "\n");
  
  str2 = "";
  for i = 1:cantidadpolos 
    str2 = strcat(str2, " [s - (",num2str (p(i)),")] ");
  endfor
  strlen = length (str2);
  for i = 1:strlen
    str = strcat(str, "-");
  endfor
  str = strcat(str, "\n");
  str = strcat(str, str2);
endfunction  
function mostrarExpresionCPG (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  helpdlg (obtenerExpresionCPG(ft), "Expresion ceros, polos, ganancia");
endfunction

function mostrarGrafico (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  grafico = figure;
  set (grafico,"name","Grafico de ceros y polos");
  set (grafico,"numbertitle","off");
  pzmap (ft);
  title ("Ceros y polos");
  xlabel ("Eje real");
  ylabel ("Eje imaginario");
endfunction

function estable = estabilidad (polos)
  cantidad = length (polos);
  for i = 1:cantidad
    if (real (polos(i)) > 0)
      estable = "El sistema es inestable";
      return;
    endif
  endfor
  estable = "El sistema es estable";
endfunction

function mostrarEstabilidad (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  [z,p,g] = tf2zp(ft);
  helpdlg (estabilidad (p),"Estabilidad");
endfunction

function mostrarTodo (handlesource,event,numBox,denBox,gainBox,hayGanancia)
  ft = procesarFT (numBox,denBox,gainBox,hayGanancia);
  [z,p,g] = tf2zp(ft);
  mostrarGrafico(handlesource,event,numBox,denBox,gainBox,hayGanancia)
  helpdlg (strcat (evalc ("ft"),"\n",evalc ("z"),"\n",evalc ("p"), ...
  "\n",evalc ("g"),"\nExpresion CPG\n",obtenerExpresionCPG(ft),"\n\n",estabilidad (p)),"Todos los datos");
endfunction
   
abrirVentanaPrincipal();
